---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx.fullname" . }}-config
  labels: {{- include "nginx.labels" . | nindent 4 }}
data:
  nginx.conf: {{- include "nginx.config" .Values.nginx | nindent 4 -}}
