{{- $root := . -}}
{{- with .Values.nginx.http.config_files -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx.fullname" $root }}-http-config
  labels:
    {{- include "nginx.labels" $root | nindent 4 }}
data:
  {{- range . }}
  {{ .filename }}: |-
    {{- include "nginx.http_generic_config" . | trim | nindent 4 }}
  {{- end }}
{{- end }}
