{{- $root := . -}}
{{- with .Values.serviceAccount -}}
{{- if and (hasKey . "create") .create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nginx.serviceAccountName" $root }}
  labels: {{- include "nginx.labels" $root | nindent 4 }}
  {{- with .annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if hasKey . "automount" }}
automountServiceAccountToken: {{ .automount }}
{{- end }}
{{- end }}
{{- end }}
